ruleDirs:
  - C:\Users\boer\Documents\GitHub\vscode-plugin\.sg\rules
testConfigs:
  - testDir: C:\Users\boer\Documents\GitHub\vscode-plugin\.sg\rule-tests
utilDirs:
  - C:\Users\boer\Documents\GitHub\vscode-plugin\.sg\utils
